=begin
Problem 2:

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
=end

def fibonacci n
  fib1 = 0
  fib2 = 1
  while n > 0
    n -= 1
    tmp = fib1
    fib1 = fib2
    fib2 = tmp + fib2
  end
  fib2
end

answer_002 = 0
i = 0
fib = fibonacci i
while fib <= 4000000
  if fib.even?
    answer_002 += fib
  end
  i += 1
  fib = fibonacci i
end

puts "Answer: #{answer_002}\n"

# Answer: 4613732
