/*
  Even Fibonacci numbers
  Problem 2

  Each new term in the Fibonacci sequence is generated by adding the previous
  two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed
  four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

int fibonacci(int n){
  int fib1 = 0;
  int fib2 = 1;
  int tmp = 0;

  while(n > 0){
    n--;
    tmp = fib1;
    fib1 = fib2;
    fib2 += tmp;
  }

  return fib1;
}

int main(){
  int answer_002 = 0;
  int i = 0;
  int fib = fibonacci(i);

  while(fib <= 4000000){
    if(fib % 2 == 0)
      answer_002 += fib;
    fib = fibonacci(i);
    i++;
  }

  printf("Answer: %i\n", answer_002);
}

// Answer: 4613732
